package env

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/anastanveer653/envy/internal/crypto"
)

const (
	EnvyDir      = ".envy"
	StoreFile    = "store.enc"
	ConfigFile   = "config.json"
	DefaultEnv   = "development"
)

// Secret holds a single key-value secret
type Secret struct {
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
	Note      string    `json:"note,omitempty"`
}

// EnvStore holds all secrets for all environments
type EnvStore struct {
	Version     string                       `json:"version"`
	Environments map[string]map[string]Secret `json:"environments"`
	PasswordHash string                      `json:"password_hash"`
}

// Store manages the encrypted environment store
type Store struct {
	path     string
	password string
	data     *EnvStore
}

// NewStore creates or opens an existing store
func NewStore(projectRoot, password string) (*Store, error) {
	storePath := filepath.Join(projectRoot, EnvyDir, StoreFile)

	s := &Store{
		path:     storePath,
		password: password,
	}

	if _, err := os.Stat(storePath); os.IsNotExist(err) {
		s.data = &EnvStore{
			Version:      "1.0.0",
			Environments: make(map[string]map[string]Secret),
			PasswordHash: crypto.HashPassword(password),
		}
		return s, nil
	}

	if err := s.load(); err != nil {
		return nil, err
	}

	if s.data.PasswordHash != crypto.HashPassword(password) {
		return nil, errors.New("incorrect password")
	}

	return s, nil
}

// Set stores a secret in the given environment
func (s *Store) Set(env, key, value, note string) error {
	if s.data.Environments[env] == nil {
		s.data.Environments[env] = make(map[string]Secret)
	}

	existing, exists := s.data.Environments[env][key]
	createdAt := time.Now()
	if exists {
		createdAt = existing.CreatedAt
	}

	s.data.Environments[env][key] = Secret{
		Value:     value,
		UpdatedAt: time.Now(),
		CreatedAt: createdAt,
		Note:      note,
	}
	return s.save()
}

// Get retrieves a secret from the given environment
func (s *Store) Get(env, key string) (Secret, error) {
	envSecrets, ok := s.data.Environments[env]
	if !ok {
		return Secret{}, fmt.Errorf("environment '%s' not found", env)
	}

	secret, ok := envSecrets[key]
	if !ok {
		return Secret{}, fmt.Errorf("key '%s' not found in environment '%s'", key, env)
	}

	return secret, nil
}

// Delete removes a secret from the given environment
func (s *Store) Delete(env, key string) error {
	if s.data.Environments[env] == nil {
		return fmt.Errorf("environment '%s' not found", env)
	}
	delete(s.data.Environments[env], key)
	return s.save()
}

// List returns all keys in the given environment
func (s *Store) List(env string) ([]string, error) {
	envSecrets, ok := s.data.Environments[env]
	if !ok {
		return nil, fmt.Errorf("environment '%s' not found", env)
	}

	keys := make([]string, 0, len(envSecrets))
	for k := range envSecrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys, nil
}

// ListEnvironments returns all environment names
func (s *Store) ListEnvironments() []string {
	envs := make([]string, 0, len(s.data.Environments))
	for e := range s.data.Environments {
		envs = append(envs, e)
	}
	sort.Strings(envs)
	return envs
}

// GetAll returns all secrets for an environment (map copy)
func (s *Store) GetAll(env string) (map[string]Secret, error) {
	envSecrets, ok := s.data.Environments[env]
	if !ok {
		return nil, fmt.Errorf("environment '%s' not found", env)
	}
	result := make(map[string]Secret, len(envSecrets))
	for k, v := range envSecrets {
		result[k] = v
	}
	return result, nil
}

// ExportEnv exports an environment as a .env file string
func (s *Store) ExportEnv(env string) (string, error) {
	secrets, err := s.GetAll(env)
	if err != nil {
		return "", err
	}

	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	output := fmt.Sprintf("# Generated by envy — environment: %s\n# %s\n\n", env, time.Now().Format(time.RFC3339))
	for _, k := range keys {
		v := secrets[k]
		if v.Note != "" {
			output += fmt.Sprintf("# %s\n", v.Note)
		}
		output += fmt.Sprintf("%s=%s\n", k, v.Value)
	}
	return output, nil
}

func (s *Store) load() error {
	data, err := os.ReadFile(s.path)
	if err != nil {
		return fmt.Errorf("failed to read store: %w", err)
	}

	decrypted, err := crypto.Decrypt(string(data), s.password)
	if err != nil {
		return fmt.Errorf("failed to decrypt store: %w", err)
	}

	s.data = &EnvStore{}
	if err := json.Unmarshal([]byte(decrypted), s.data); err != nil {
		return fmt.Errorf("failed to parse store: %w", err)
	}
	return nil
}

func (s *Store) save() error {
	dir := filepath.Dir(s.path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}

	jsonData, err := json.MarshalIndent(s.data, "", "  ")
	if err != nil {
		return err
	}

	encrypted, err := crypto.Encrypt(string(jsonData), s.password)
	if err != nil {
		return err
	}

	return os.WriteFile(s.path, []byte(encrypted), 0600)
}




